Foundriesio test cases
Linaro/test-definitions pull request #333
Opened 2022-01-05 12:57 UTC by mwasilew

This patch series contains set of tests used to test Foundries.io Linux microPlatform. It focuses on the OS features - mainly aktualizr-lite daemon. The daemon is used to handle OTA software updates.

2022-01-10 13:26 UTC, nareshkamboju reviewed
Here in the plan,
http://github.com/mwasilew/test-definitions.git

Do you want to keep personal name space "mwasilew" in repo url ?

2022-01-10 13:29 UTC, nareshkamboju commented on automated/linux/ota-rollback/download-update.sh
> +        u) UBOOT_VAR_TOOL="${OPTARG}";;
Indentation.

2022-01-12 10:27 UTC, mwasilew commented
@nareshkamboju I guess it's catch-22. Right now plan points to my repository because the tests are there, not in Linaro's repo. I guess it can be corrected in PR. I'll fix it.

2022-01-12 14:29 UTC, mwasilew commented on automated/linux/ota-rollback/download-update.sh
> +        u) UBOOT_VAR_TOOL="${OPTARG}";;
fixed

2022-01-12 14:29 UTC, mwasilew commented
@nareshkamboju fixed both comments

2022-01-18 14:14 UTC, nareshkamboju commented on automated/linux/aklite-download-interrupt/aklite-download-interrupt.sh
> +    # sleep 5 min
s/sleep 5 min /sleep 1 s/

2022-01-18 14:22 UTC, nareshkamboju commented on automated/linux/ota-rollback/verify-reboot.sh
> +	-t <kernel|uboot>
indentation

2022-01-18 14:27 UTC, nareshkamboju requested changes
Minor comments on indentation and inline comments.

2022-01-18 14:27 UTC, nareshkamboju commented on automated/linux/ota-rollback/verify-reboot.sh
> +		t) TYPE="${OPTARG}";;
indentation

2022-01-18 14:27 UTC, nareshkamboju commented on automated/linux/ota-rollback/verify-rollback.sh
> +	-t <kernel|uboot>
indentation

2022-01-18 14:27 UTC, nareshkamboju commented on automated/linux/ota-rollback/verify-rollback.sh
> +		t) TYPE="${OPTARG}";;
indentation

2022-01-18 14:27 UTC, nareshkamboju commented on automated/linux/ota-rollback/verify-rollback.sh
> +		h|*) usage ; exit 1 ;;
indentation

2022-01-20 13:23 UTC, nareshkamboju approved these changes

2022-01-20 13:24 UTC, merged