automated: linux: add docker-corrupt OTA test
Linaro/test-definitions pull request #408
Opened 2022-11-29 20:21 UTC by brenwoo

Verify successful rollback after OTA upgrade containing corrupt docker app.

Signed-off-by: Brendan Wood <brendan.wood@foundries.io>

2022-12-05 11:59 UTC, mwasilew requested changes

2022-12-05 11:59 UTC, mwasilew commented on automated/linux/ota-rollback/verify-rollback.sh
> +        if (journalctl --no-pager -u aktualizr-lite | grep "Finalization has failed; reason: apps start failure"); then
maybe there is a way to determine the state by MESSAGE and RESULT variables from aklite?

2022-12-13 20:03 UTC, mwasilew requested changes
Looks very good. Just 2 minor edits and we're good to go.

2022-12-13 20:03 UTC, mwasilew commented on automated/linux/ota-rollback/verify-rollback.sh
> +    	ref_bootfirmware_version_after_rollback=0
tabs vs. spaces

2022-12-13 20:03 UTC, mwasilew commented on automated/linux/ota-rollback/verify-rollback.sh
> +	report_skip "app-rollback"
too long indentation

2022-12-16 10:08 UTC, mwasilew commented
LGTM

2022-12-16 12:48 UTC, roxell commented
I'm ok with this too.

@brenwoo would it be cleaner to do http://ix.io/4iKg ? maybe you can do that in a followup patch?

2022-12-19 06:53 UTC, merged

2022-12-19 06:54 UTC, nareshkamboju commented
@brenwoo  Thanks for your contribution.
@mwasilew and @roxell Thanks for the review.